= plan for documenting

Необходимо описать
1. Использование камер глубины в задачах навигации внутри и вне помещений. - 20 стр.
2. Использование RGB-камер (моно, стерео) в задачах навигации внутри и вне помещений. - 20 стр.
3. Описание алгоритмов ORB SLAM, особенно методов ИИ, используемых в них. - 50 стр.

Ссылки на литературу, листинги отдельных алгоритмов, примеры, картинки.
Сделать 3 отдельных word документа (14 шрифт, полуторный интервал).
Контекст - документ ПЗ для Интеллект Н.



== Использование камер глубины в задачах навигации внутри и вне помещений. - 20 стр.

.задачи навигации внутри и вне помещений
* какие задачи (навигация объекта, контроль с внешних камер(локализация, навигация, трекинг))
* какие носители (коптер, робот, автомобиль, человек со смартфоном )
* контекст


.задачи навигации внутри и вне помещений
* движение по маршруту, позиционирование
* контроль окружения (определение объектов, людей) - избежание столкновений
* todo about navigation

TODO:: describe navigation

== Использование RGB-камер (моно, стерео) в задачах навигации внутри и вне помещений. - 20 стр.



== Описание алгоритмов ORB SLAM, особенно методов ИИ, используемых в них. - 50 стр.


прочитать статью, сделать общий обзор



* Описание алгоритмА ORB SLAM
* слам интро, что такое, постановка, цели, .....

ORB SLAM2
ORB SLAM3
