= reading


тезаурус



СПО АТБ-С
Специальное программное обеспечение абонентского терминала
СПО МОБ
Специальное программное обеспечение мобильного терминала на базе смартфона или планшета с ОС Аврора или ОС Android
НУ
Навигационное устройство – Абонентский терминал либо смартфон
СПО КСО ИН
Специальное программное обеспечение комплекта серверного оборудования комплекса интеллектуальной платформы навигации
ИНС
Инерциальная навигационная система
IMU
Инерциально-измерительный блок
ЛСН
Локальная система навигации
СЧ ПО
Специальное программное обеспечение Составная часть
Wi-Fi
Технология беспроводной локальной сети с устройствами на основе стандартов IEEE 802.11
BLE
Беспроводная технология связи Bluetooth с низким энергопотреблением
ИИ, AI
Искусственный интеллект, Artificial Intelligence
ML
Методы машинного обучения
SLAM
Simultaneous localization and mapping, одновременное позиционирование и картографирование

SAM
Smoothing and mapping, алгоритм оптимизации карты (iSAM, GTSAM)
Sensor fusion
Алгоритмы комплексирования различной навигационной информации

Карта препятствий (Occupancy Map, Grid)
Облако точек (PointCloud)
Плотное облако точек(Octomap, dense point cloud)


include::rgbd-camera-usage.adoc[leveloffset=1]


include::rgb-camera-usage.adoc[leveloffset=1]
include::orb-slam.adoc[leveloffset=1]

// - 50 стр.
