= Использование RGB-камер (моно, стерео) в задачах навигации внутри и вне помещений.
// - 20 стр.

:imagesdir: images
:toc: preamble

:author: timur chikichev
:email: t.chikichev@navigine.ru

:pygments-style: Coderay

:toc: macro


== LSD-SLAM

Масштабный Прямой УДАР со стереокамерами Cameras
Jakob Энгель, Jили¨rg Stuckle¨ckler, Дэниел Кремерс

Рассмотрим метод LSD-SLAM в качестве альтернативы для метода ORB-SLAM в контексте применения для локализациии и навигации по камере.

Полномасштабный алгоритм для стерео камеры (stereo LSD-SLAM), который работает в режиме реального времени с высокой частотой на стандартных устройствах без необходиимости аппаратного ускорения.  

В отличие от в разреженных методов на основе характерных точек, этот метод напрямую выравнивает изображения основываясь на соответствии высокой контрастности всех пикселов изображений, в том числе положении характерных элементов углов, кромок, градиентов и текстурных элементов. 
Алгоритм одновременно оценивает глубину в этих пикселях по двум типам стереосигналов: статическое стерео с помощью калиброванной стереокамеры с фиксированным взаимным положением камер, а  также временное многовидовое стерео, использующее движение камеры.

Используя оба источника информации, алгоритм может даже оценить глубину пикселей, которые не являются полностью определеннными при использовании только фиксированного базового метода стереокамеры.  
Использование стереокамеры позволяет доограничивать систему для избежания масштабного дрейфа в предсказанных координатах глубины, что часто происходит в чистом моно SLAM методах.  

Авторы также предлагают разумный подход для использования условия инвариантности освещенности сцены, что должно позволитьработу в сценах с агрессивными изменениями яркости между кадрами. Зафиксировано значительно улучшение в производительности для реалистичных сценариев использования метода. 




Введение
Визуальная одновременная локализация и отображение (SLAM) в условиях real-time ограничений реального времени has традиционно been решались с использованием разреженных interest точек интереса, поскольку они уменьшают the большое количество пикселей на изображениях до небольшого количества объектов. Только недавно были предложены прямые методы, способные работать в режиме реального времени proposed , которые позволяют избежать the зависимости от интересующих точек, но вместо этого выполняют выравнивание изображений и 3D-реконструкцию непосредственно на пикселях, используя ограничения на фотоконсистенцию. Предпосылка прямых подходов по сравнению с методами, основанными на точках интереса, заключается в том, что информация об изображениях может использоваться плотно. Не требуется ручная разработка interest point детекторов точек интереса, дескрипторов и matching процедур сопоставления is , что would также ограничивает алгоритм SLAM algorithm to определенным типом функции – обычно используются только углы изображения . Вместо этого в методах прямого ШЛЕМА богатый набор пикселей способствует to depth оценке глубины и отображению.
В этой статье мы предлагаем первый крупномасштабный подход прямого визуального СЛЭМА для стереокамер, работающий в режиме реального времени на процессорах. Наш метод оценивает глубину с неопределенностью в пикселях с высоким intensity градиентом интенсивности, восстанавливая полуплотную карту глубины онлайн. Он одновременно отслеживает движение твердого тела с помощью фотометрического выравнивания изображений based на основе the depth карт глубины.
В нашей предыдущей работе над крупномасштабным прямым монокулярным шлемом (LSD-SLAM) мы получили глубину в ключевых кадрах by с помощью стереоизображения по пикселям между the текущим и the ключевым кадром.
Эта работа has была частично поддержана by грантом CR 250/9-2 (Картирование по запросу) Немецкого исследовательского фонда (DFG) и грантом 16SV6394 (AuRoRoll) of BMBF.
Дж    . Энгель,  Дж    . С.Т.Уклер¨ckler  и  Д.  Cremers    Кремерс     withработают на  the    Depart- ment кафедре компьютерных наук Технического университета of Мюнхена, Германия
{энгель,штекль,кремерс}@in.tum.de


Рис. 1. Стерео LSD-SLAM-это полностью прямой метод SLAM для стереокамер. Он работает на частоте 30 Гц на процессоре, вычисляя точное перемещение камеры , а также полузатянутые вероятностные карты глубины. Мы используем как статическую, так и временную стереосистему и корректируем аффинные изменения молний, делая метод точным и надежным в реальных сценариях. Некоторые примеры показаны в the прилагаемом видео.

Движение камеры отслеживается в направлении ключевого кадра с помощью фотометрического выравнивания изображения. Для ШЛЕМА в глобальном масштабе ключевые кадры are выровнены по отношению друг к другу , а их позы оптимизированы с помощью оптимизации графика. Поскольку масштаб реконструкции не виден в монокулярном шлеме, мы дополнительно оптимизируем for the масштаб для прямого image выравнивания изображения as , а также для pose graph оптимизации графика позы.
В этой работе мы соединяем временную стереосистему of monocu- монокулярного LSD - ШЛЕМА со статической стереосистемой из a стереокамеры с фиксированной базовой линией. В каждом пикселе наш метод стерео LSD-SLAM method интегрирует статические , а также временные stereo стереосигналы в оценку в зависимости от наличия. Это сочетает в себе свойства of монокулярной структуры из движения with fixed-baseline stereo с оценкой глубины стереоизображения с фиксированной базой estimation в a одном SLAM методе ШЛЕМА. В то время как статическое стерео эффективно удаляет масштаб как свободный параметр, временные стереосигналы позволяют оценить глубину по базовым линиям за пределами небольшой базовой линии стереокамеры. Темпоральное стерео не ограничено одним определенным (например , горизонтальным) направлением, таким как статическое стерео. Скорее его базовая линия соответствует поступательному движению между кадрами.  Кроме того, мы предлагаем a метод for обработки illumination изменений освещенности при прямом выравнивании изображения, что значительно повышает proves надежность robustness of нашего алгоритма в реалистичных условиях.
Мы оцениваем стерео ЛСД-СЛЭМ на the популярной Китти

эталонные данные и наборы данных из EuRoC Challenge 3 для микро-летательных аппаратов (МВА), демонстрирующие современную the-art эффективность of нашего подхода.
СОПУТСТВУЮЩАЯ РАБОТА
Sparse interest-point-based approaches to visual odometry and В последние годы были широко исследованы подходы к визуальной одометрии и шлему, основанные на разреженных точках интереса have been extensively investigated in recent . The Термин визуальная одометрия has был введен в the наполовину окончательной работе of Nister et и др. [1] , которые предложили разреженные методы for оценки the движения of монокулярных , а также stereo стереокамер путем последовательного frame-to-frame сопоставления кадров. Chiuso et и др. [2] предложили один из первых методов монокулярного шлема с возможностью работы в реальном времени , основанный на нелинейной фильтрации. Дэвисон [3] предложил MonoSLAM, способный работать в реальном времени, основанный на EKF метод, который продемонстрировал SLAM в небольших рабочих пространствах. Разреженные точки интереса отслеживаются в формулировке EKF-SLAM, чтобы восстановить движение камеры и (глобальное) 3D-положение точек интереса. Другим примером разреженного монокулярного шлема является параллельное отслеживание и отображение (PTAM [4]), которое разделяет и распараллеливает оптимизацию для отслеживания и отображения в a bundle adjustment рамках настройки пакета. Совсем недавно Strasdat Strasdat и др. [5] включил масштаб в качестве параметра в optimization подход к оптимизации на основе ключевых кадров to для разреженного монокулярного ШЛЕМА.
Используя настройку стереокамеры с фиксированной базовой линией, масштаб становится непосредственно видимым. Одна из ранних работ применяет EKF-SLAM к редкому набору точек интереса [6]. Пас и др. [7] комбинируйте монокулярные стереосигналы со стереосистемой с фиксированной базовой линией в разреженной иерархической структуре EKF-SLAM .
Прямые методы, которые позволяют избежать обнаружения разреженных точек интереса have , недавно привлекли внимание к визуальному ШЛЕМУ. Одним из основных преимуществ прямых методов перед разреженными является то, что они не полагаются на функции изображения, созданные вручную, которые ограничивают тип информации, которую можно использовать на последующих этапах обработки. В домене RGB-D [8], [9], [10], прямые методы have стали самыми современными благодаря своей высокой точности и эффективности. LSD-SLAM [11] был первым крупномасштабным методом прямого монокулярного ШЛЕМА. В LSD-SLAM движение камеры отслеживается в направлении ключевых кадров, для которых с помощью вероятностной фильтрации оцениваются полуплотные карты глубины. Pose graph Оптимизация графика позирования выравнивает the ключевые кадры в a глобально согласованном расположении. Эксплицитность LSD-SLAM учитывает scale смещение масштаба при pose graph оптимизации графика позы и находит a единую согласованную шкалу. Для стереокамер подход прямой визуальной одометрии был предложен Comport и др. [12]. Их подход явно не explicitly восстанавливает глубину, но использует quadrifo- четырехмерные ограничения на пиксели, которые соответствуют стерео , для camera motion оценки движения камеры. В методе прямого стерео method в [13] карта несоответствий интегрируется с течением времени, в то время как движение стереокамеры отслеживается путем прямого выравнивания изображения с использованием расчетной глубины. Ключевые кадры в нашем подходе также интегрируют глубину, в то время как вместо этого мы используем вероятностную фильтрацию. Наш подход сочетает стереосигналы с фиксированной базовой линией, полученные при настройке статической камеры, с временной стереосигнализацией из различных базовых линий, вызванных движущейся камерой. Мы объединяем это с системой SLAM на основе позы-графика, которая глобально оптимизирует the позы of the ключевых кадров. A Еще одним важным вкладом of нашей работы является the коррекция for

Рис. 3. Каждый ключевой кадр поддерживает a Gaussian probability распределение вероятностей Гаусса на обратной глубине для всех пикселей, имеющих достаточный градиент изображения, чтобы можно было оценить глубину. Слева направо: Изображение интенсивности, полуплотная обратная depth карта глубины, обратная depth variance карта дисперсии глубины.

аффинное освещение изменяется , чтобы обеспечить прямое image выравнивание изображения в реалистичных настройках. В отличие от предыдущих методов [14], [15], мы оптимизируем параметры аффинной коррекции освещения поочередно, что позволяет применять различные схемы отклонения выбросов при выравнивании изображения и lighting коррекции освещения.

ЛСД-СЛЭМ СО СТЕРЕОКАМЕРАМИ CAMERAS
LSD-SLAM [11]-это подход к локализации и отображению на основе ключевых кадров approach , который использует the следующие основные шаги:
The Движение of the камеры is отслеживается в направлении a опорного ключевого кадра на карте. Новые ключевые кадры создаются, если камера переместилась слишком далеко от существующих ключевых кадров на the карте.
Глубина в текущем опорном ключевом кадре оценивается по стереопараметрам, основанным на отслеживаемом движении (временная стереопараметрия).
Позы ключевых кадров делаются глобально согласованными путем взаимного прямого выравнивания изображений и оптимизации графика позирования.
В стерео LSD-SLAM the глубина in ключевых кадров is in дополнительно оценивается непосредственно по статическому стерео (см. рис. 2). Существует ряд преимуществ этого подхода в том, чтобы полагаться исключительно на временное или исключительно на статическое стерео. Статическая стереосистема позволяет оценить абсолютный масштаб мира и не зависит от движения камеры. Однако статическая стереосистема ограничена постоянной базовой линией (во многих случаях с фиксированным направлением), что эффективно ограничивает the производительность to определенным диапазоном. Временная стереосистема не ограничивает производительность определенным диапазоном, как показано в [11]. Один и тот же датчик может be использоваться в очень малых и очень больших средах и легко перемещаться между the ними. с the другой стороны, он не обеспечивает масштабирования и требует невырожденного движения камеры. Дополнительным преимуществом объединения временной и статической стереосистемы является то, что доступно несколько базовых направлений are : в то время как статическая стереосистема обычно имеет a горизонтальную базовую – линию, которая не позволяет оценивать глубину по горизонтальным краям, временная стереосистема позволяет for дополнить the depth карту глубины by , указав другие motion направления движения.
В деталях мы вносим the следующие ключевые вклады:
Мы обобщаем LSD-SLAM на стереокамеры, комбинируя ing временную и статическую стереосистему в a прямом real-time методе SLAM, способном работать в реальном времени SLAM .
Мы явно моделируем изменения освещенности во время прямого image выравнивания изображения, тем самым делая the метод очень надежным даже в сложных реальных условиях.
Мы проводим a систематическую оценку по двум базовым показателям


Рис. 2.   Обзор on the стереосистемы LSD-SLAM .

наборы данных из реалистичных робототехнических приложений, демонстрирующие ing самые современные возможности of нашего подхода.
Обозначение
Мы используем жирные заглавные буквы для матриц (таких как R) и жирную lower строчную букву для векторов (таких как ξ). The Оператор [ ]n выбирает n-ю строку матрицы. На протяжении всей статьи мы используем d для обозначения the обратной of the глубины z of a точки, т. Е.,
d = z−1.
в стерео ЛСД-шлема, карта функционирует как набор ключевых кадров кЯ = Я,Я, я,Р, Д, Я, Вменя .  Каждый кадр состоит из
камеры, но снятые в один и тот же момент времени), а также с временной стереосистемы (т. Е. с использованием изображений с одной и той же физической камеры, снятых в разные моменты in времени).
Статическое стерео: Мы определяем дисперсность статического стерео в пикселе путем поиска соответствия вдоль его эпиполярной линии в другом стереоизображении. В нашем случае со стереопрямленными изображениями этот поиск может быть очень эффективно выполнен по горизонтальным линиям.
В качестве меры соответствия мы используем фотометрическую погрешность SSD более пяти пикселей along вдоль линии сканирования. После субпикселя



в янвэрзе глубина карте ДЯ : ΩДЯ    Р  и его вariance карте вя :  ΩДЯ    Р  .   Глубина  и  вariance  являются  только  поддерживать на одном из изображений в стереопаре, мы всегда используйте левое изображение как система отсчета. Мы предполагаем, что область изображения Ω  R2 задается в координатах стереопрямленного изображения, т. Е. Внутренние и внешние параметры камеры известны априори. The Область ΩDi    Ω  является the полуплотным ограничением на the пиксели , которые are выбраны для depth оценки глубины.
We Обозначим координаты пикселей через u = (ux uy 1)T . 3Д установки п = (пх пг пз 1)т проецируется в плоскости изображения путем сопоставления у = π(П) := К ((Р,х/р,з) (пг/р,з) 1)т , где к - это на камеры матрицы.  В сопоставлении п = π−1(ю, д)   :=  d−1K−1u T 1  инвертирует проекцию с the обратной глубиной d.
Depth Оценка Глубины
Мы оцениваем геометрию сцены в ключевых кадрах. Каждый ключевой кадр поддерживает гауссовы распределения вероятностей на обратной глубине of a подмножества of пикселей. Это подмножество is выбрано в качестве the пикселей с высокой image gradient величиной градиента изображения, поскольку эти пиксели предоставляют богатую структурную информацию и более надежные disparity оценки различий , чем пиксели в textureless областях без текста.
[16].  Если в Гауссовой до С виду д и стандарт де- отклонение σд О в обратную глубина есть в наличии, мы ограничивают в выдаче С [Д 2σд, д + 2σд].  В практике, в выдаче интервал состоит только из очень немногих пикселей для всех, но Ново инициализирован гипотезы, значительно ускоряя время поиска и сокращения на вероятность в поисках либо неправильные или неоднозначный матч. Согласно двум источникам ошибок, мы ожидаем, что пиксели с градиентами изображения, близкими к вертикальным, или с низким градиентом изображения вдоль горизонтального направления, не дают точных оценок несоответствия. Следовательно, мы пренебрегаем этими пикселями для статического стерео.
при a new инициализации нового ключевого кадра , мы немедленно выполняем статическое стерео для обновления и обрезки карты глубины распространения. В частности, обрезка удаляет пиксели, которые были заблокированы, и мы заполняем отверстия, возникающие в результате прямого искажения карты глубины. Впоследствии мы также используем статическое стерео из отслеживаемых неключевых кадров и интегрируем полученную информацию о несоответствии в ключевой кадр, на котором они отслеживались: на первом этапе гипотеза обратной глубины в пикселе u в the ключевом кадре is преобразуется в the новый кадр,

На рисунке 3 показан an пример of такой a полуплотной глубины depth


карта и связанная variance с ней карта отклонений. Мы инициализируем the глубину
карта путем распространения depth гипотезы глубины из the предыдущей
ключевой кадр. Карта глубины map is впоследствии обновляется with новыми

наблюдения в a pixel-wise системе фильтрации глубины по пикселям . Мы
также упорядочьте the depth карты глубины пространственно и удалите выбросы.
согласно to the pose оценке позы ξ. The Распространяемая гипотеза
is используется в качестве предварительного для a стереоискателя , и the соответствующий

В отличие от монокулярного ШЛЕМА, глубина is оценивается как
наблюдаемая глубина d'
obs
и observation дисперсия наблюдения σ2    равна

из статического стерео (т. Е. с использованием изображений с разных физических    объектов. Наконец, the наблюдение is преобразуется обратно в

of этого остатка [11]. Целью оптимизации objective для отслеживания a текущего кадра в направлении a ключевого кадра является


где ρ - a надежная весовая функция; мы выбираем ρ в качестве the нормы Хубера. Обратите внимание, что в отличие от [12], мы выравниваем только Il по Il . Хотя можно было бы добавить фотометрические ограничения к the новому правильному изображению Ir, мы заметили , что это может уменьшить
точность на практике: как правило, the базовая линия от Il до Ir

Рис. 4. Временные и Статический стерео: например, сцена, где как физическое стерео (epipolar линии параллельны в переулок-разметка на дороге) и статические стерео (epipolar линии являются параллельными , чтобы в горизонтальных мост) только не для захвата всей информации присутствует.  Наш комбинированный подход предохранители информация из обоих, и , следовательно, может восстановить все в этой сцене.
is намного больше , чем до Il , что приводит к большему количеству выбросов от окклюзий и отражений.
Поскольку fused глубина плавления is доступна в ключевых кадрах, мы добавляем геометрические остатки для keyframe-to-keyframe выравнивания между ключевыми кадрами,


(4)
первоначально отслеживание новых кадров, поскольку они еще не имеют связанных depth оценок глубины . The Объединенная цель состоит в том, чтобы



неключевые кадры могут only быть сгенерированы только для пикселей с an существующей предыдущей гипотезой - новые гипотезы are only генерируются только во время стерео на ключевом кадре или из временной стереосистемы. Этот процесс is схематично показан на рис. 2.
б) Временная стереосистема: После отслеживания мы оцениваем ity несоответствие между the текущим кадром и the опорным ключевым кадром и объединяем его в ключевой кадр. Опять же, мы используем только пиксели, для которых ожидаемая обратная ошибка глубины достаточно мала. Мы определяем эту неопределенность по нескольким критериям: градиент изображения должен быть достаточно большим, не должен быть параллелен эпиполярной линии, а пиксель не должен находиться близко к эпиполю. Мы любезно ссылаемся на [16] для получения более подробной информации об этом методе. Хотя мы используем простую 5-пиксельную ошибку SSD, мы исправляем affine изменения аффинного освещения с the помощью аффинного отображения , найденного во время
отслеживание, как will будет описано в разделе III-C. Обратите внимание, что для
Обратите внимание, что эта формулировка использует полную информацию о глубине , доступную для обоих кадров, включая распространенные и объединенные наблюдения из других stereo стереопар (см. Раздел III-B). Это отличается от неявного квадрифокального подхода, как, например, в [12].
Мы минимизируем эти цели using , используя iteratively итеративно взвешенный алгоритм Левенберга-Марквардта algorithm в a левой композиционной формулировке: начиная с начальной оценки ξ(0), на каждой итерации приращение δξ(n), умноженное на левое is , вычисляется путем решения для минимума приближения второго порядка of E, с фиксированными весами:

временная стереосистема, the геометрическая погрешность обычно is выше , чем

для статического стерео, поскольку относительная поза камеры зависит от прямого выравнивания изображения. Эта оценка позы часто менее точна , чем автономная калибровка внешней калибровки между stereo camera парой стереокамер.
Прямое Image выравнивание изображения с Аффинной Lighting коррекцией освещения
Мы определяем движение камеры motion между двумя изображениями , используя прямое выравнивание изображения. Мы используем этот метод для отслеживания движения камеры в направлении опорного ключевого кадра. Он также используется для оценки относительных ограничений позы между ключевыми кадрами для оптимизации графика позы. Наконец, мы предлагаем надежный метод to compensate компенсации аффинных lighting изменений освещения.
Прямое Image выравнивание изображения: The Относительная поза между
является the производной of the сложенного вектора of остатков r(ξ) with относительно to  a left-multiplied приращения s, умноженного на левое, , JT WJ приближение Гаусса-Ньютона approximation of the гессиана of E, а W диагональная матрица, содержащая веса. Затем новая оценка is then получается путем умножения с the вычисленным обновлением
ξ(n+1)  = δξ(n)  ◦ ξ(n).    (12) Мы используем схему от грубого к тонкому для повышения эффективности и basin сходимости convergence of the оптимизации.
Предполагая, что остатки статистически независимы, обратная of the зависимость Гессиана от the последней итерации (JT WJ)-11 является оценкой ковариации Σξ of a left-multiplied приращения s, умноженного слева , на the конечный минимум, то есть




Рис. 5. Аффинная Lighting коррекция освещения: Две сцены с сильными lighting изменениями освещения. Справа мы показываем диаграмму рассеяния всех остатков после прямого image выравнивания изображения; The Зеленая линия показывает the наилучшее соответствие с нашего подхода, в то время the как красная линия показывает the наилучшее соответствие для всех пикселей. обратите внимание, как на нее is сильно влияют выбросы, вызванные окклюзиями и чрезмерно открытыми пикселями, которые легко распознаются на the диаграмме рассеяния.


Аффинной коррекции освещения: прямое выравнивание изображения в основном основано на the brightness constancy предположении о постоянстве яркости, которое is сильно нарушается , например , при экспозиции камер exposure

Рис. 6. Результирующий график позы для последовательности 00 из Kittiтеста Китти, содержащий 1227 ключевых кадров и 3719 ограничений. В таблице показано how , сколько ограничений have было предпринято для отслеживания down to which pyramid уровня пирамиды, а well также the среднее время , необходимое для взаимного image выравнивания изображений на этом уровне пирамиды. Обратите внимание, как большинство неверных кандидатов на замыкание цикла отбрасываются уже при очень грубом разрешении, что происходит очень быстро. За всю последовательность потребовалось всего 43 больших попытки замыкания цикла, чтобы найти все замыкания цикла в the последовательности.

Минимизация в a, b is выполняется путем итеративной минимизации
E    (a, b) :=  Σ ρ    aIl (u) + b  − Il (u')    (15)


с u' := π (p'), что можно be сделать в закрытой форме:
Σ    Il (u)Il (u′)


время is настраивается таким образом, чтобы оно лучше соответствовало the средней яркости of the
a  = Σ
Ял (у')Ял (у')

это is инвариантно к аффинным lighting изменениям освещения, например using , с использованием
нормализованная перекрестная корреляция (NCC) вместо простой суммы of квадратов различий (SSD) для сопоставления. Здесь мы предлагаем аналогичный подход и модифицируем фотометрические остатки (6) , чтобы они были инвариантны к аффинным lighting изменениям освещения:

rI (ξ) := aIl (u) + b − Il (p').    (14)
Вместо совместной оптимизации для a, b и ξ в общей формулировке er- ror formulation, мы alternate чередуем (1) a один Levenberg- Marquardt шаг обновления Левенберга - Марквардта step в ξ (исправление a, b) и (2) a полную минимизацию по a, b (исправление ξ), используя различные weighting схемы взвешивания. Это мотивировано наблюдением, что ξ и a, b react очень differently по-разному реагируют на выбросы:
На минимум в a, b сильно влияют закрытые и чрезмерно открытые пиксели, поскольку они, как правило, ”тянут” в одном и том же неправильном направлении. С другой стороны, он, как правило, уже хорошо ограничен небольшим количеством остаточных выбросов - поэтому мы используем простую,агрессивную ошибку SSD с отсечением, т. е. ρa, b(r) := min δmax, r2 . На рис. 5 показаны две примеры сцен и полученное в результате аффинное отображение с and without отклонением выбросов и без него.
The Минимум в ξ is гораздо меньше подвержен by выбросам, так как они, как правило, ”тянутся” в разных направлениях, отменяя друг друга. В свою очередь, может случиться так, что некоторые dimen- sions of размеры ξ ограничены только небольшим количеством пикселей, которые изначально имеют высокий остаток - удаление их как выбросов will приведет the к тому, что оценка to сойдется к неправильному локальному минимуму. Поэтому мы используем схему взвешивания, предложенную в [11], которая только уменьшает вес but , но  не удаляет остатки.
b∗ =     1      Il (u')    a∗Il (u)  ,    (17)
|ΩL|  i
с the набором of вкладов
ΩL :=  u ∈ ΩD  | ρa,b  aIl (u) + b  − Il (u')  < δмакс.  .
Найденные аффинные параметры a, b затем используются во tem-время временнойporal стереосистемы и во the consistency время проверки согласованности on depth распространения по глубине.
Хлопок на Основе Ключевого Кадра SLAM
Как только a ключевой кадр i будет завершен – то есть, после того, как он будет заменен в качестве tracking ссылки для отслеживания и will не будет получать никаких дальнейших depth обновлений глубины , – он is добавляется в the график позы, который is постоянно оптимизируется в фоновом режиме. Ограничения получены путем выполнения выравнивания SE(3) с учетом остаточной глубины и аффинной lighting коррекции освещения для a набора of возможных loop- closure кандидатов на замыкание цикла: отслеживание is выполняется на всех ключевых кадрах
Kj1 , ..., Kjn , которые
находятся на a физическом расстоянии of less менее (60 + р · 0,05.) м..
имеют a разницу в viewing направлении обзора of less менее (35+
р · 0,01.)◦.
, где p - the длина of the кратчайшего соединительного пути в графике ключевых кадров между двумя ключевыми кадрами в метрах, которая служит консервативным приближением к накопленной- mulatedотносительной ошибке позирования. Для очень больших карт можно найти дополнительные замыкания цикла, используя методы поиска изображений на основе внешнего вида, такие как FAB-КАРТА [17]. Однако в наших экспериментах мы не сочли это необходимым. Для ключевых кадров с p  100 ммы используем относительную позу, полученную путем компоновки ребер вдоль этого пути , в качестве инициализации для прямого image выравнивания изображения, в противном the identity is случае используется идентификатор.

ttотношение: поступательный RMSE дрейф RMSE (%), av. over в среднем с интервалами от 100 м до 800 м. intervals.
rrel: вращательный RMSE дрейф RMSE (град на 100 м), av. over в среднем с интервалом от 100 м до 800 м. intervals.
tabs: абсолютное значение RMSE после 6DoF выравнивания 6DoF, в метрах.
время: время однопоточных вычислений time на кадр в миллисекундах.

Для каждого кандидата jk мы независимо вычисляем ξjki и ξij путем минимизации (9). Только в том случае, если две оценки статистически схожи, т. е. если
e(ξj   i, ξij   ) := (ξj   i  ◦ ξij   )T Σ−1(ξj   i  ◦ ξij   )    (18)
Рис. 7. Наборы данных EuRoC с микро-летательного аппарата. Вверху: реконструкция с первой (слева) и третьей (справа) траекторий. Внизу: Выбор изображений с the третьей траектории, отображающих сильные lightning изменения молнии (с первого по второе изображение), motion размытие движения (третье изображение) и виды с небольшой текстурой (четвертое изображение).

B. Kitti Набор данных Китти
Мы оценили наш метод на хорошо известном Kittiнаборе данных Китти. В таблице I обобщены результаты как для стерео LSD-шлема с and замыканием петли, так и без него (VO). Приведенные результаты given

разница между точностью и computational скоростью вычислений – см. также

достаточно мал, они добавляются как ограничения к позе-графику. Здесь Adjjki является сопряжением ξjki в SE(3). Чтобы speed ускорить the удаление of неверных loop-closure кандидатов на замыкание петли,
мы применяем эту проверку согласованности после каждого уровня пирамиды. только если она пройдет, прямое выравнивание изображения будет продолжено на следующем более высоком разрешении. Это позволяет отбросить большинство неверных кандидатов с only очень небольшим количеством потраченных впустую вычислительных re- ресурсов: на рисунке 6 показано how , сколько ограничений where отслеживается на каком уровне пирамиды для одной из самых длинных последовательностей в the Kitti наборе данных Kitti.
Результаты
Мы представляем результаты, полученные с помощью Stereo LSD-SLAM (1) на хорошо известном Kittiнаборе данных Kitti и (2) на трех последовательностях , записанных с микро-летательного аппарата (МВА), летящего в помещении, взятых из the EuRoC Challenge 3. Мы оцениваем как время выполнения, так и точность для различных настроек параметров. Хотя наша реализация сильно использует несколько ядер процессора, все временные интервалы, приведенные в этой главе, относятся к однопоточному threaded выполнению на an процессоре Intel i7 - 4900MQ CPU , работающем на
2,8 Ггц.
A. EuRoC Набор данных EuRoC
Мы запускаем стерео LSD-SLAM по набору данных EuRoC, полученному из a МВА , летающего по a комнате which , которая equipped оснащена системой захвата движения для получения достоверной информации. Набор данных содержит 3 траектории со все более агрессивным движением. Инжир. На рис. 7 показана полученная реконструкция. Абсолютная- поступательная RMSE составляет 6,6 см, 7,4 см и 8,9 см для первой, второй и третьей траекторий соответственно. В этом наборе данных мы удалили первые и последние 150 изображений для каждой траектории, так как в некоторых из них only видна только поверхность земли is .
Раздел IV-D. В the оценочных последовательностях 11-21 мы достигаем среднего трансляционного RMSE в 1,21% для полного ШЛЕМА, который в настоящее время занимает второе место среди стереометрических методов. Стерео LSD - SLAM is , однако , намного быстрее , чем методы , достигающие аналогичной точности. Повышенная ошибка по сравнению с тестовыми последовательностями 00-10 обусловлена наличием большого количества движущихся объектов в 20 и 21, которые иногда приводят к сбою прямого выравнивания изображения (раздел IV-F). Кроме того, Kittiэталонный маркер Kitti only обеспечивает только изображения , снятые с частотой 10 Гц при движении со скоростью до 80 км/ч , что является сложной задачей для прямых методов, поскольку они хорошо используют небольшие внутрикадровые движения.

Визуальная одометрия против ШЛЕМА
Здесь мы оцениваем возможность выполнения крупномасштабных замыканий петли при запуске системы полного ШЛЕМА , а well также эффект от выполнения замыкания петли только в небольшом окне of the последних l кадров l - эффективного превращения стереофонического LSD-ШЛЕМА в Визуальную Одометрию. При l = 0, no image выравнивание изображения без геометрической ошибки не выполняется, и используется только поза из the начального frame выравнивания кадра is . Для этого сравнения мы рассматриваем только Kittiпоследовательности Китти, которые содержат значительные замыкания цикла, т. е. 00, 02, 05, 06 и 07. На рисунке 8 обобщен результат: отчетливо видно, что выполнение полного ШЛЕМА значительно уменьшает долгосрочный дрейф, что неудивительно. Однако это сопряжено с повышенными вычислительными затратами: при выполнении полного SLAM общий требуемый вычислительный бюджет более чем удваивается (также см. табл. I), поскольку полный график позы должен быть оптимизирован, и необходимо отслеживать многие ограничения на замыкание цикла. Все цифры в этом разделе относятся к запуску стереофонического LSD-ШЛЕМА с половинным разрешением.


Рис. 8. Визуальная одометрия по сравнению с SLAM: Слева: поступательный дрейф по различным- ferent evaluation длинам оценочных сегментов для разных размеров of окна pose-graph оптимизации позы window l. Для l = , наш метод выполняет полный SLAM; следовательно the , поступательный дрейф уменьшается при оценке по более длинным сегментам (до 0,5%). Справа: 6DoF-выровненные траектории последовательности Китти 00. Хотя выполнение локальной оптимизации позы-графика немного повышает локальную точность, оно не может устранить дрейф на длинных сегментах.



Рис. 10. Примеры сцен с движущимися объектами и сильными перекрытиями. Справа мы показываем остаточную интенсивность после прямого выравнивания изображения (небольшие значения are показаны in серым цветом; большие отрицательные / положительные остатки are показаны красным

Рис. 9.   Image Разрешение изображения: На графике показано the среднее поступательное значение RMSE
tt соответствует различным разрешениям изображений, а также требуемому времени вычислений. Стерео LSD-SLAM позволяет плавно менять одно на другое-при разрешении изображения в одну восьмерку от оригинала он работает на частоте 400 Гц (VO) / 145 Гц (SLAM) в одном потоке, при этом средний дрейф составляет всего 3,5% (VO) и 2,5% (SLAM).


Влияние of Image разрешения изображения
A Прекрасным свойством of стерео LSD-SLAM является то, что the достигнутая точность очень изящно снижается с уменьшением разрешения изображения, в то время как требуемый вычислительный бюджет быстро сокращается. На самом деле, мы были в состоянии работать как полный шлем , как хорошо , как во о самой Китти набор данных на вниз , чтобы один восемь из в оригинал постановления, т. е., 154 46 пикселей, и до сих пор достичь разумного в смысле поступательного смещения на 2,5% (шлема) и 3.5% (за кадром) – по значительно сниженным вычислительных затрат, работает в 15 реальном времени (шлема) и 40 в режиме реального времени (во).  В результате это обобщены на рис.  9.
Performance Анализ производительности
В таблице II мы суммируем the вычислительное время , необходимое для каждой части алгоритма. Все тайминги указаны в миллисекундах на кадр. Для более низких разрешений изображения отбираются с пониженной выборкой на этапе предварительной обработки, так как обычно это можно сделать без дополнительных аппаратных затрат (привязка пикселей). Можно четко be заметить , что все части of the алгоритма – , за исключением оптимизации позы – графика, напрямую масштабируются в зависимости от количества пикселей на изображении. Только при очень низком разрешении операции, не зависящие от разрешения, такие как инвертирование гессиана во LM время минимизации пленки – , начинают to оказывать a визуальное воздействие.
Движущиеся объекты и Окклюзии
A remarkable property of direct Замечательным свойством прямого выравнивания изображений является ”свойство блокировки” [18]: При наличии alignment ap- proaches is the ”locking property” [18]: In the presence
черный / белый). В то время как в первых двух примерах прямое выравнивание изображения фиксируется на правильном движении, в последнем примере оно фиксируется на неправильном движении в сцене – движущихся автомобилях – и не удается правильно выровнять два изображения. Это can видно seen по the остаткам вокруг the lane разметки полосы движения.


из множества движений или выбросов подход от грубого к тонкому приводит к тому, что прямые методы to lock фиксируют the наиболее доминирующее движение within the validity в радиусе действия the линеаризации. A надежная функция взвешивания затем позволяет минимизировать влияние пикселей, не принадлежащих этому движению. На рисунке 10 показаны три примера, в которых большие части изображения перемещаются или становятся закрытыми: в первых двух примерах правильно идентифицируется доминирующее движение, в то время как в третьем примере выравнивание изображения фиксируется на движущихся автомобилях на переднем плане. Мы наблюдали эту проблему только в 20 – й последовательности the Kittiтеста Kitti, поскольку есть много автомобилей, движущихся с одинаковой скоростью-возможно, доминирующее движение в сцене-это движение автомобилей. Для онлайн-оценки мы решаем эту проблему, удаляя все точки в определенном объеме перед автомобилем только для этой последовательности. Тем не менее, в будущей работе мы могли бы воспользоваться преимуществами нашего подхода, например, путем сегментации движения сцены на ряд движений твердого тела ([18], [19], [20]).

Качественные Результаты
Мы показываем на рис. 11 некоторые качественные результаты оцененных esti-полуплотных mated semi-dense depth карт глубины и the результирующих облаков точек. Обратите внимание, как оценивается глубина почти во всех областях, в которых есть информация о градиенте, и сколько мелких деталей (знаков, фонарных столбов) восстанавливается. Кроме того, включение временной стереосистемы позволяет to оценить глубину для строго горизонтальных структур, таких как линии power электропередачи lines , видимые на некоторых of the изображениях.





Рис. 11.   Point Облака точек и depth карты глубины для the Kitti набора данных Kitti (последовательности 08,14,15,18), работающие в полном разрешении. Также смотрите the прикрепленное видео.


выводы

Мы предложили стерео LSD-SLAM, новый прямой подход к ШЛЕМУ со стереокамерами. Наш метод использует статические стереосигналы с фиксированной базовой линией, а также временные стереосигналы с переменной базовой линией. Статическая стереосистема обеспечивает точную глубину в пределах эффективного рабочего диапазона стереокамеры. Это также устраняет неоднозначность масштаба и трудности с вырожденным движением вдоль линии обзора, проблему, присущую монокулярному- ularшлему, который использует только временную стереосистему. С другой стороны, при использовании временной стереосистемы глубина может оцениваться в переменных базовых направлениях , соответствующих to the поступательному движению между кадрами.
Наш метод напрямую выравнивает изображения, используя фотометрические и геометрические остатки в полуплотном наборе пикселей. Мы выбираем пиксели, в которых имеется достаточная информация для статической или временной- стереооценки. В отличие от методов, основанных на разреженных точках интереса, наш подход не ограничивается определенным типом объектов изображения features , которые are извлекаются на a decoupled processing этапе раздельной обработки перед to image выравниванием изображения.
В наших экспериментах Stereo LSD-SLAM демонстрирует самые современные результаты на the популярном Kitti benchmark наборе данных Kitti benchmark для стереодометрии и SLAM на автономных автомобилях. Стерео LSD-SLAM также performs очень точно выполняет сложные последовательности, записанные с помощью микро-летательного аппарата (MAV) для EuRoC Challenge 3. Оба набора данных очень сложны для чисто монокулярного подхода, так как движение происходит в основном вдоль the прямой of видимости (автомобили) или может mainly состоять в основном из поворотов (MAV).
В будущей работе мы рассматриваем возможность расширения нашего подхода к multi-camera настройке нескольких камер за пределы бинокулярных stereo стереокамер. Объединение датчиков с инерциальной или GPS-информацией может еще больше повысить точность и надежность в the местном и the глобальном масштабе. Наконец, мы планируем заняться сегментацией и оценкой движения нескольких тел. Таким образом, наш метод восстановил бы не только recover the доминирующее движение на the изображениях, но и the движение of дальнейших независимых движущихся объектов.

